version: "3.9"

services:
    goods:
        build: ./crudserver/
        hostname: goods
        container_name: goods
        restart: always
        env_file:
            - .env
        ports:
            - ${GOODS_API_PORT}:${GOODS_API_PORT}
        depends_on:
            - postgres
            - redis
            - nats
        networks:
            webservices:
    logserver:
        build: ./logserver/
        hostname: logserver
        container_name: logserver
        restart: always
        env_file:
            - .env
        depends_on:
            - clickhouse
            - nats
        networks:
            webservices:
    postgres:
        image: postgres
        container_name: postgres
        hostname: postgres
        restart: always
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        volumes:
            - .data/postgres:/var/lib/postgresql/data
        networks:
            webservices:
    redis:
        image: redis
        container_name: redis
        hostname: redis
        restart: always
        env_file:
            - .env
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}
        networks:
            webservices:
    nats:
        image: nats
        container_name: nats
        hostname: nats
        restart: always
        env_file:
            - .env
        ports:
            - ${NATS_PORT}:${NATS_PORT}
        networks:
            webservices:
    clickhouse:
        image: clickhouse/clickhouse-server
        container_name: clickhouse
        hostname: clickhouse
        restart: always
        env_file:
            - .env
        environment:
            CLICKHOUSE_USER: ${CLICKHOUSE_USER}
            CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
            CLICKHOUSE_DB: ${CLICKHOUSE_DB}
        ports:
            - ${CLICKHOUSE_PORT}:${CLICKHOUSE_PORT}
        volumes:
            - .data/clickhouse:/var/lib/clickhouse
        networks:
            webservices:
networks:
    webservices:
        external: true